[package]
name = "quanty-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "The executor thread that answers protocol requests for QuantyDB"

[dependencies]
quanty-auth.workspace = true
quanty-core.workspace = true
quanty-exec.workspace = true
quanty-proto.workspace = true
quanty-ql.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
quanty-server.workspace = true

[dev-dependencies]
quanty-auth.workspace = true
quanty-core.workspace = true
quanty-exec.workspace = true
quanty-proto.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
quanty-server.workspace = true
